### ISSUE TITLE
Hackmd's 1.20 mod list cannot be viewed. Please return it normal :)

### ISSUE THREAD

**Issue by EnderOre** [TagnumElite/ProjectE-Integration#104]
![image](https://github.com/TagnumElite/ProjectE-Integration/assets/66881284/6430f802-b5c8-46ad-8132-ca0d167d2d86)

1.20's page is 403 Forbidden
You do not have permission to view this resource
![image](https://github.com/TagnumElite/ProjectE-Integration/assets/66881284/c5973532-d5dd-4c7e-bc51-e2795ca3e030)

**Comment by TagnumElite** [comment]
Woops, let me fix

**Comment by TagnumElite** [comment]
Should be public now
