### ISSUE TITLE
Missing EMC values for Botania in 1.20.1

### ISSUE THREAD

**Issue by xenogray** [TagnumElite/ProjectE-Integration#127]
### Prerequisites

- [ x ] I am running the latest version
- [ x ] I have made sure there is no duplicate issue

### Details

- MC Version: 1.20.1
- Mod Version: 7.2.1

## Description

Botania was a supported mod and its items had EMC values up until the previous MC version. It's missing in 1.20.1 version

### Expected behavior
Botania items to have EMC values.

### To Reproduce
1. Have Botania
2. Have ProjectE integration
3. Check any Botania item, they will have no EMC value.

## Logs
Not sure if it is necessary ?

- latest.log
- crash-\*.log (if applicable)

Very sorry if it's the wrong  category but I was very surprised to see that Botania suddenly became unsupported after all this time.

Thank you !

**Comment by TagnumElite** [comment]
Added back support in 7.2.2
