### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by festro** [TagnumElite/ProjectE-Integration#139]
### Prerequisites

- [x] I am running the latest version
- [x] I have made sure there is no duplicate issue

### Details

- MC Version: 1.20.1
- Mod Version: 7.2.4

## Description
Stops loading on startup giving an error

### Expected behavior
the game to load and not give an error?

### To Reproduce
1. Do This 
2. Do That 
3. Then This 

## Logs

- latest.log
[latest.log](https://github.com/user-attachments/files/17056690/latest.log)

- crash-\*.log (if applicable)
[crash-2024-09-19_02.15.11-fml.txt](https://github.com/user-attachments/files/17056651/crash-2024-09-19_02.15.11-fml.txt)

The error I receieve
ProjectE Integration (projecteintegration) encountered an error during the common_setup event phase
		java.lang.ClassCastException: class com.tagnumelite.projecteintegration.addons.IceAndFireAddon$IAFDragonForgeMapper

**Comment by TorinnTheDragon** [comment]
Seems to me an issue with Ice and Fire mod to me

**Comment by festro** [comment]
That's what I figured, disabling either of the mods and the game runs fine.

**Comment by TorinnTheDragon** [comment]
> That's what I figured, disabling either of the mods and the game runs fine.

If you just go back to version 7.2.2 seems to work just fine till they fix the issue

Cause I'm having the exact same issue on my modpack too.

**Comment by TagnumElite** [comment]
Yeah, I was planning to fix this yesterday but the modmaven was down. Will
try to take another crack at it today before work.

**Comment by TagnumElite** [comment]
Found the issue, I forgot to change the @CustomRecipeMapper to @RecipeTypeMapper because IaF moved to RecipeTypes. Will push the fix now.

**Comment by TagnumElite** [comment]
Should be fixed in 7.2.5
