### ISSUE TITLE
Cant Generate new worlds while mod is on {1.12.2}

### ISSUE THREAD

**Issue by MaxMaker12** [TagnumElite/ProjectE-Integration#141]
### Prerequisites

- [X ] I am running the latest version
- [X ] I have made sure there is no duplicate issue

### Details

- MC Version: 1.12.2
- Mod Version: 2.5.0

## Description

whenever i use the mod i cant generate a new world it just gets stuck on building terrain
(the log files are using the newest beta version but the same thing happened before i updated to 2.5.0)

### Expected behavior
the world to be made and i can play my modpack i made LOL

### To Reproduce
1. Do This 
2. Do That 
3. Then This 

## Logs
- latest.log
- 2024-10-24-7.log

https://gist.github.com/MaxMaker12/4904a7726b206da871e8491e93c1043f

its weird i have no idea what is causing this i know disabling this mod stops it but i assume its a this mod doesn't like another one but i have no idea which one i added Expanded Equivalence thinking it would lessen the load which didn't help (and sounds silly now i say it LOL) so idk what to do i hope it can be fixed

(this would be eaiser to test cause im trying to upload my modpack but its not been approved yet so i cant link that so it cant be as eaisely recreated)

**Comment by MaxMaker12** [comment]
Expanded Equivalence causes it too idk wtf is going on anymore i assume its one mod really doesn't like anything EMC related but it makes no sense its so weird any help would be amazing

**Comment by TagnumElite** [comment]
This problem seems to be caused by `Equivalent Energistics` `java.lang.AbstractMethodError: Method com/mordenkainen/equivalentenergistics/items/ItemEMCCell.getStoredEmc(Lnet/minecraft/item/ItemStack;)J is abstract`
