### ISSUE TITLE
Chisel support

### ISSUE THREAD

**Issue by pupnewfster** [TagnumElite/ProjectE-Integration#16]
It would be nice if there was support for chisel, at least to the point of only having to set one EMC value per item for chisel only blocks. For example `unlimited chisel works` adds a lot of various chisel variants of blocks, and it is a pain having to set the EMC value of each and every one.

**Comment by TagnumElite** [comment]
Chiel uses oredict, so setting emc to an oredict is possible, I don' know about unlimited chisel works though.

**Comment by pupnewfster** [comment]
I don't think chisel *purely* uses oredict given it is also possible to add custom ones using ModTweaker https://docs.blamejared.com/en/#Mods/Modtweaker/Chisel/Carving/ So my guess is they have some system to keep track of the conversions; you can probably look at ModTweaker to see how chisel keeps track of them.

Also I vaguely recall at some point trying to add chisel variants to the oredict and it not working properly for some reason.
