### ISSUE TITLE
Extendedcrafts compressor recipe 

### ISSUE THREAD

**Issue by TheNimbleNinja** [TagnumElite/ProjectE-Integration#23]
the way the extended crafts compressor recipes are calculated are wrong its taking the original items emc and just overlaying that. when it should be taking the amount of items that will make a singularity and the catalyst to make the singularity.

**Comment by TagnumElite** [comment]
You're right, screwed that one up. Will fix shortly.

**Comment by TagnumElite** [comment]
Should be fixed in 2.3.1!
