### ISSUE TITLE
Galacticraft support

### ISSUE THREAD

**Issue by NicosaurusRex99** [TagnumElite/ProjectE-Integration#26]
**Is your feature request related to a problem? Please describe.**
Galacticraft compatability would be nice because crafting a large amount of everything can be tedious at the best of times

**Describe the solution you'd like**
Could you please add Galacticraft support

If needed here is the API link https://www.micdoodle8.com/mods/galacticraft/downloads/dev

**Describe alternatives you've considered**
Additionally i could manually add each value but a small plugin would be highly appreciated

**Comment by TagnumElite** [comment]
I would need to include the mod in the libs folder to which I suspect the mod author may have a heart attack about. For now, due to being unable to find a maven. Support will come out but not right now.

**Comment by TagnumElite** [comment]
Okay, I have figured out a way of getting the files from the CI. Support will come sooner than later.

**Comment by NicosaurusRex99** [comment]
cool
