### ISSUE TITLE
Blood Magic, Calculator and Extra Botany support

### ISSUE THREAD

**Issue by TheNimbleNinja** [TagnumElite/ProjectE-Integration#3]
hey i would like some support for extra botany and blood magic so i can make my pack have multiple pack modes as i cant have differnt emc values for differnt pack modes  as any custom emc value i give will be used throught the  whole pack

**Comment by TheNimbleNinja** [comment]
oh and add support for the calculator mod :)

**Comment by TagnumElite** [comment]
Todo:
- [x] Extra Botany
- [x] Blood Magic
- [x] Calculator
