### ISSUE TITLE
Split vis crystals into all the different ones

### ISSUE THREAD

**Issue by Louis2747** [TagnumElite/ProjectE-Integration#30]
When i try to get some vis crystals the only option is "%s vis crystals" and when i take some it just gives me a random vis crystal.

Solution:
Split the "%s vis crystals" option into all the different vis crystals.

![2020-04-07_13 17 34](https://user-images.githubusercontent.com/52701949/78663403-57386380-78d2-11ea-9e03-2fb6289e5e5d.png)

**Comment by TagnumElite** [comment]
That is a problem with ProjectE not supporting NBT (Not that I blame them). I can't do anything about vis crystals.
