### ISSUE TITLE
Mekanism problems

### ISSUE THREAD

**Issue by justintyang** [TagnumElite/ProjectE-Integration#34]
So right now, Mekanism has several items that are not integrated properly. The basic versions like wire and energy cubes have correct EMC, and can be recorded into the Transmutation Tablet. However passed Advanced, the EMC is incorrect, and the item will not record. Please fix, if you are still around.

**Comment by TagnumElite** [comment]
This is a problem with ProjectE not using NBT. I can't fix this.
