### ISSUE TITLE
[1.16.5]Some compat not working

### ISSUE THREAD

**Issue by ASUT0R0** [TagnumElite/ProjectE-Integration#35]
**Describe the bug**
AE2, Extended Crafting, and Woot compat not working.

**To Reproduce**
1. Download and install mods.
2. Launch game.
3. Join world.
4. See JEI.
5. Items crafted via supported recipe type don't have EMC.

**Expected behavior**
Crafted items have EMC.

**Desktop (please complete the following information):**
 - OS: Windows10

**Mod Version**
 - Forge : 36.2.4
 - ProjectE : PE1.0.1B
 - ProjectE Integration : 4.0.3
 - Applied Energistics 2 : 8.4.1
 - Extended Crafting : 3.1.6
 - Woot : 1.0.8.0
 - Draconic Evolution : 3.0.15.415
 - Immersive Engineering : 5.0.3-138
 - Compact Crafting : 1.0.0-beta.3
 - Cucumber Library : 4.1.10
 - Brandon's Core : 3.0.10.237
 - CodeChicken Lib 1.8.+ : 4.0.3.434
 
**Additional context**
Tested with the above mods, JEI and datapack for compact crafting recipe. Nothing else.
DE, IE, and Compact Crafting compat work correctly.

**Comment by TagnumElite** [comment]
Hmm, weird, will look into this.

**Comment by TagnumElite** [comment]
Ok,

AE: I mistyped the modid, woops. Also made other mistakes
Extended Crafting: Works fine
Woot: Also works as intended.

It seems to be something else.

**Comment by TagnumElite** [comment]
Okay, I found the problem, it was Immersive Engineering Squeezer mapper. Will upload an update shortly.
