### ISSUE TITLE
Error Calculating EMC with Compact Crafting Installed

### ISSUE THREAD

**Issue by ThisisCanada98** [TagnumElite/ProjectE-Integration#42]
### Prerequisites

- [ x] I am running the latest version
- [x ] I have made sure there is no duplicate issue

### Details

- MC Version: 1.16.5
- Mod Version: projecte-integration-1.16.5-4.2.0.

## Description

When having both compact crafting and POI installed causes an error and no emc being attached to any item

### To Reproduce
1. Do This <Launch a modpack of only Compact crafting and Project E + POI>
2. Do That <Enter World>
3. Then This <Get an error in the log about Error calculating EMC>

## Logs
https://gist.github.com/ThisisCanada98/ec865d578f59660ed1943737c0326d63

**Comment by TagnumElite** [comment]
Hmm, looks like the mod has been updated. Will fix soon.

**Comment by TagnumElite** [comment]
Should be fixed in version `4.3.0`.
