### ISSUE TITLE
[Request] Industrial Foregoing support.

### ISSUE THREAD

**Issue by SSkizz** [TagnumElite/ProjectE-Integration#43]
IF has some recipes that ProjectE's mapper doesn't see. Liquid latex, or Latex Bucket, does not get assigned a value for example, and furthermore, the Simple Machine Frame crafted in the Dissolution Chamber also does not get assigned a value.

Would be cool to see IF integration. 

Cheers.

**Comment by SSkizz** [comment]
Edit: In addition to Industrial Foregoing, Mekanism support for the same reasons would be sick. 😎

**Comment by TagnumElite** [comment]
I believe mekanism implemented their own support or was that only partial?
