### ISSUE TITLE
Crash on entering main menu

### ISSUE THREAD

**Issue by ChromaPIE** [TagnumElite/ProjectE-Integration#45]
### Prerequisites

- [x] I am running the latest version
- [x] I have made sure there is no duplicate issue

### Details

- MC Version: 1.16.5
- Mod Version: 4.4.2

## Description

Game crashes on entering main menu. With Not Enough Crashes the game won't quit, but it forces the game to show a "Saving world" screen and back to the main menu upon clicking Singleplayer or video settings button. 80% sure it's caused by incompat with mods like Rubidium (a Forge fork of Sodium). Here to see if it's unsolvable or not.

### Expected behavior
The game behaves the way it should be.

### To Reproduce
1. Mod list will be provided below in the log.
2. Enter the game
3. Shows a Not Enough Crashes crash screen, you can still enter the main menu
4. Click the Singleplayer or Video Settings button
5. Kaboom. Weirdly shows a "Saving world" screen and goes back to the main menu.

## Logs
https://paste.ubuntu.com/p/nwSnpCHQ5y/

**Comment by TagnumElite** [comment]
Ah, found it I think.

**Comment by TagnumElite** [comment]
Should be fixed in `v4.4.4`.
