### ISSUE TITLE
Crash upon world load after updating to PEI v2.0.0 from v1.5.0

### ISSUE THREAD

**Issue by ate0ate** [TagnumElite/ProjectE-Integration#5]
After using Project E Integration v1.5.0 for quite some time now without issue I now get this crash when attempting to load my 1.12.2 world after updating to the recent PEI v2.0.0.

https://pastebin.com/fc6sn5CG

I am currently using forge 14.23.5.2823 in a probably excessive personal pack. I did attempt deleting the old PEI config and retrying without success. Reverting to v1.5.0 does indeed work as it used to. If there is any further information I could provide please let me know.

**Comment by TagnumElite** [comment]
I noticed this after testing with Embers - Rekindled in a modpack, if you go into the config and switch off embers dawnstone anvil mapper the pack won't crash anymore.

```cfg
plugins {
    embers: {
        B:enable_dawnstone_anvil_mapper=false
    }
}
```

**Comment by TagnumElite** [comment]
For now however, I've added an TryCatch clause, so if any other Plugins/Mappers fail, the game shouldn't crash anymore. (Hopefully)

**Comment by ate0ate** [comment]
Interesting. I think I will try disabling the config for Embers Rekindled's Dawnstone Anvil mapper as you have suggested as well. I have encountered other issues with different mods before that mentioned that. Would toggling that option off have any negative effects that you know of? 
I'll also give your new build a try before doing so to test things out as well. Thank you very much for the swift fix!

**Comment by TagnumElite** [comment]
Disabling the mapper will only disable the EMC Conversion for the dawnstone anvil recipes. This means any recipe outputs using the dawnstone anvil won't get any automated EMC values

**Comment by ate0ate** [comment]
Understood. Thank you much for the help. I tested the PEI v2.0.1 release very briefly without toggling the Dawnstone Anvil mapper off and the world loads without issue now. All else appears to be working as intended though I obviously didn't dive too deeply into anything that quickly. I'll go ahead and close this now seeing as the issue is resolved. Thank you again for your efforts.
