### ISSUE TITLE
Linkage with Endless

### ISSUE THREAD

**Issue by mango-buff** [TagnumElite/ProjectE-Integration#51]
Can the author link with Endless? 
CurseForge link: [https://www.curseforge.com/minecraft/mc-mods/endless-fake](https://www.curseforge.com/minecraft/mc-mods/endless-fake)
GitHub link: [https://github.com/yuoft/endless](https://github.com/yuoft/endless)

**Comment by mango-buff** [comment]
By the way, this is a Chinese mod.

**Comment by TagnumElite** [comment]
Should be fixed in 4.4.5

**Comment by mango-buff** [comment]
Thank you.
