### ISSUE TITLE
Support for the Chipped mod

### ISSUE THREAD

**Issue by oliverrook** [TagnumElite/ProjectE-Integration#53]
**Is your feature request related to a problem? Please describe.**
The chipped mod adds in a ton of stone blocks that count towards most recipes that have "forge:stone" in the recipe. Because of this, with the Chipped mod installed, every single recipe that uses normal stone is no longer given an EMC value due to it not supporting the crafting system of the mod.

**Describe the solution you'd like**
The ideal solution would be adding in the crafting system from the chipped mod, which I believe should be fairly simple as there's only one and it's GUI based.

**Describe alternatives you've considered**
If that's not possible, or too hard, perhaps make it so that anything with "forge:stone" in the recipe is considered to have the EMC value of default vanilla stone.

**Additional context**
This causes issues with a *lot* of recipes, and requires *tons* of manual emc edits to fix, as there's dozens of decorative stone blocks in the mod, and the only other solution is to manually calculate every recipe with stone in it.

**Comment by TagnumElite** [comment]
Support has been added in 1.18 from 5.2.4, working on 1.16 support now
