### ISSUE TITLE
(1.18.2-Latest) Game Breaking Issues With Chipped

### ISSUE THREAD

**Issue by PhweeDev** [TagnumElite/ProjectE-Integration#57]
ProjectE Integration completely breaks both itself and ProjectE, leaving no EMC for ANY item with Chipped 2.0.0, ProjectE, CTM, and the latest ProjectE Integration. **It only breaks when adding ProjectE Integration.** 

This is caused after updating to Chipped 2.0.0. See https://github.com/terrarium-earth/Chipped/issues/149

**Comment by TagnumElite** [comment]
I will fix this shortly
