### ISSUE TITLE
It is recommended to convert EMC through JEI compatible with most mods

### ISSUE THREAD

**Issue by gjmhmm8** [TagnumElite/ProjectE-Integration#58]
It is recommended to convert EMC through JEI compatible with most mods

**Comment by TagnumElite** [comment]
I have looked into doing this in the past but it feels too hacky and probably won't work. I haven't looked into this for the newish projecte api but JEI and ProjectE EMC mapping may not happen at the same order or in the correct order. I also don't believe all recipes will be mapped correctly.

**Comment by gjmhmm8** [comment]
What if you only use jei recipes for compatibility on mods that are not adapted?

**Comment by gjmhmm8** [comment]
After all, there are too few compatible mods now, and similar E6E ATM7 mod packages are not well compatible
