### ISSUE TITLE
Cant access the supported mods list, it says i dont have permission to view

### ISSUE THREAD

**Issue by pwnr227** [TagnumElite/ProjectE-Integration#69]
### Prerequisites

- [x] I am running the latest version
- [x] I have made sure there is no duplicate issue

### Details

- MC Version: 
- Mod Version: 

### To Reproduce
1. Do This 
2. Do That 
3. Then This 

## Logs

- latest.log
- crash-\*.log (if applicable)

**Comment by TagnumElite** [comment]
I'll fix this now, woops.
