### ISSUE TITLE
Support for Pam's Harvestcraft

### ISSUE THREAD

**Issue by abrachoo** [TagnumElite/ProjectE-Integration#7]
It would be nice if all of the new foods, seeds, and whatnot from Pam's Harvestcraft had EMC values. I'm tired of trying to input them all in myself.

**Comment by TagnumElite** [comment]
I've added HarvestCraft support for Grinder/Presser and Water Filter recipes. I've also added EMC to some items, I will need suggestions for the other items.

**Comment by darthvader45** [comment]
Some EMC values for the oredictionary entries forge:fruits and such that existed back in 1.12.2 (with different names ofc).  Sorry to necro a 3-year old issue.
