### ISSUE TITLE
crash with Mekinism

### ISSUE THREAD

**Issue by ShawnRHayes** [TagnumElite/ProjectE-Integration#8]
https://paste.dimdev.org/cohudibedi.mccrash

**Comment by ifficles** [comment]
Same here;

https://paste.ee/p/erRMA

downgrading to the previous version of projecte integration

**Comment by TagnumElite** [comment]
Mekanism 9.6.7.360 Moved the recipes around, will be fixed shortly

**Comment by TagnumElite** [comment]
Should be fixed, let me know of any problems.
