### ISSUE TITLE
[1.18.2] Draconic Evolution Fusion Crafting support

### ISSUE THREAD

**Issue by YourlordAdam** [TagnumElite/ProjectE-Integration#81]
**Is your feature request related to a problem? Please describe.**
The 1.18.2 version of ProjectE Integration seems to be missing support for Draconic Evolution's Fusion Crafting.

**Describe the solution you'd like**
For support for DE to be readded in 1.18.2

**Describe alternatives you've considered**
Tried other ProjectE mod supports none of which support Draconic Evolution in MC 1.18.2

**Comment by TagnumElite** [comment]
Should be fixed in 5.6.2
