### ISSUE TITLE
Mana and Artifice v2 removes all EMC values

### ISSUE THREAD

**Issue by JoelDohmKaratjas** [TagnumElite/ProjectE-Integration#94]
### Prerequisites

- [x] I am running the latest version
- [x] I have made sure there is no duplicate issue

### Details

- MC Version: 1.18.2
- Mod Version: 5.4.6
- Mana and Artifice: 2.0.0.28

## Description

No EMC values on any items

**Comment by TagnumElite** [comment]
This should be fixed in 5.6.0
